config/routes.rb
Mechanicalmap::Application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :apps do
    get 'embed', :on => :member
    get 'action', :on => :member
    get 'source', :on => :member
    put 'source_update', :on => :member
    get 'stats', :on => :member
    get 'create_gf_table', :on => :collection
    resources :tasks do
      get 'next', :on => :collection
      resources :answers do
        get :update #for cross domain update
      end
    end
  end

  match "/demo_generator" => "task_generators#new", :via => "get"
  match "/demo_generator" => "task_generators#create", :via => "post"

  root :to => "home#index"

end

app/views/apps/_app_menu.html.erb
      <% @start = true if @start.nil? %>

     <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      <% if @start %>
       <li><a href="<%= app_url(@app) %>"><b class="icon-play"></b> Start </a></li>
      <% end %>

      <li>
        <a  href="/apps/new?copyof=<%= @app.id %>"><b class="icon-random"></b> Remix </a>
      </li>
     <!-- <li><a tabindex="-1" href="#embed_app_<%= @app.id %>" role="button" class="btn" data-toggle="modal" data-target="#embed_app_<%= @app.id %>"><b class="icon-share"></b> Embed / Share </a></li> -->
      <li><a tabindex="-1" href="<%= stats_app_url(@app) %>"><b class="icon-signal"></b> Stats </a></li>
      <li class="divider"></li>
      <li>
        <a href="<%= source_app_url(@app) %>" target="_blank" target="_blank"><b class="icon-file"></b> Source code </a>
      </li>
      <li class="divider"></li>
      <li>
        <a  target="_blank" href="<%= @app.challenges_table_url %>"><b class="icon-hdd"></b>Challenges Data  </a>
      </li>
      <li>
        <a target="_blank" href="<%= @app.answers_table_url %>"><b class="icon-hdd"></b>  Answers Data </a>
      </li>
      <% if @app.user == current_user %>
      <li class="divider"></li>
      <li>
        <a href="<%= edit_app_url(@app) %>"> <b class="icon-wrench"></b>Admin </a>
      </li>
      <% end %>
     </ul>

<!--
   <div id="embed_app_<%= @app.id %>" class="modal fade hide in" role="dialog" aria-labelledby="myModalLabel"  aria-hidden="true">
    <div class="modal-header">
        <a href="#" class="close-button close" data-dismiss="modal">×</a><h3>Embed Crowdsourcin app </h3>
    </div>
    <div class="modal-body">
        <div class="share-url-picker">
            <div class="row share-url-row">
                <div class="inputs">
                    <p class="share-url-description">
                        Copy and paste this code into your blog or website to embed the app
                    </p>
                    <textarea class="share-embed-code" readonly="readonly"></textarea>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer" style="text-align: right;">
        <input id="close-share-embed" type="button" class="simple-button" value="Close">
    </div>

</div>  -->

app/views/apps/_form2.html.erb
<% script = capture do %>
  <%= javascript_include_tag "app_edit" %>
<% end %>
<% content_for :script, script %>

<%= semantic_form_for(@app,:html => {:class => 'form-horizontal', :id => "form_app"}) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2>Errors prohibited this app from being saved</h2>
      <%= f.semantic_errors %>
    </div>
  <% end %>

  <%= f.inputs  :name => "Basic" do %>
    <%= f.input :name, :placeholder => "name of the app"  %>

    <%= f.input :description,
                :placeholder => "Short description in HTML",
                :input_html => {:rows => 5} %>

    <%= f.input :image_url,
                :label =>"Image url",
                :placeholder => "image url" %>
  <% end %>

  <%=  f.inputs "Iframe size", :'data-embeddable' => '1' do %>
    <%= f.input :iframe_height, :input_html => { :class => 'iframe_height' } %>
    <%= f.input :iframe_width, :input_html => { :class => 'iframe_width' } %>
 <% end %>


  <%= f.inputs :name => "Problem - Cloud Elements" do %>
      <% if @edit %>
    <div style="float:right">
      <div id="link_challenges" ></div>
      <a href="action?method=index_tasks" class="btn"/>Reindexing Challenges</a>

    </div>
    <% end %>

    <%= f.input :challenges_table_url,
                :label =>"URL of Challenges data to index",
                :hint => "Created automatically if left blank",
                :placeholder => "URL of a google fusion table" %>
                 <%= f.input :task_column,
                :label => "Task column",
                :placeholder => "Column of the challenge ID to index",
                :collection=>[]  %>
 <% if @edit %>
    <div style="float:right">
      <div id="link_answers" ></div>
      <a href="action?method=delete_answers" class="btn"/>Delete Answers</a>
    </div>
    <% end %>
    <div id="link_challenges"></div>
    <%= f.input :answers_table_url,
                :label => "URL to store micro-contributions",
                :placeholder => "URL of a google fusion table",
                :hint => "Created automatically if left blank" %>




    <%= f.input :gist_url,
                :label => "UI Source Code URL",
                :placeholder => "https://gist.github.com/3028982",
                :hint => "(default code forked if left blank)" %>
  <% end %>

  <%= f.inputs :name => "Problem - Collaborative Solving strategy" do %>
  <%= f.input :redundancy,
                :label => " How many solvers per challenge? ",
                :placeholder => "3",
                :hint => "(0 for unlimited allocation)" %>
  <% end %>

  <%= f.actions do %>
  <% if @edit %>
     <%= f.submit "update", :class =>"btn btn-primary", :disable_with => 'Wait...'  %>
      <%= link_to 'delete App', @app, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger"  %>

  <% else %>
 <%= f.submit "Create & Start coding online", :class =>"btn btn-primary btn-large", :disable_with => 'Wait...'  %>
  <% end %>




  <% end %>

  </div>
<% end %>

app/views/apps/_tutorial.html.erb
<ol class="unstyled">
<li><b>1. Create the Google fusion table containing each mini challenges you want solvers try to solve</b>

<p> a. Import <a href="https://www.google.com/fusiontables/DataSource?dsrcid=implicit" target="_blank" >your xsl, csv data</a> or create an empty Google fusion table. This table
represents the list of mini-challenges to complete with a column representing the challenge ID (e.g. task_id) and any further columns for input data (e.g. the url of an image to annotate, the questions to ask etc). You can also .

  <img src='/assets/ft_input_images2.jpg' style='width:100%;border:1px solid black' />
<!--<br/> Here another table given as example.
  <img src='/assets/ft_input_table.jpg' style='width:100%;border:1px solid black' />
-->
</p>
<p><b>b. Copy the public link </b>.  click to the 'share' button at the top right.
  and make its access to 'public'. then copy the URL at the top
<img src='/assets/share.jpg' style='width:100%;border:1px solid black' /> </p>

</p>


<div class="alert alert-block alert-success fade in">
<p>I encourage you to review the Tasks data of existing open apps to get more familiar with the framework.  <a href="https://www.google.com/fusiontables/DataSource?docid=11TePGrrVCRKJ1IPY6I8wkUrmyfZ6OKELxRgLjjU">Here</a> is the task data containing a set of images to annotate, or
<a href="https://www.google.com/fusiontables/DataSource?docid=1Xm-WmlR2wnxuBusTR94V3xZygkPKUukq9x-YLoM">here </a> with a
more complex task structure </a>
to
clusters of a set of documents. We also propose specific <i>Tasks Generator </i> e.g.
  <a href="/demo_generator"> a generator GIS-related tasks</a> for analyzing a large area
by dividing it into smaller ones.
  <a href="https://www.google.com/fusiontables/DataSource?docid=1pSWNLzQE0oZSs7KJqzhjsMeT96QELkmE9gROt7E">see
the resulting table </a></p>
</div>
<span class="label label-warning">Note</span> Google fusion has <a
href="https://developers.google.com/fusiontables/docs/developers_guide#Constraints">some constraints</a> you
need to be aware. -->
</p>
</li>
<li><h4>2. Idem for the Answers table </h4>

<p> This table should contain initially 4 required columns:
  <ul><li>
answer_id = id of the answer </li>
<li> task_id = the id of the challenge answered</li>
<li> created_at = the
datetime of
the answer </li>
<li>user_id = the user's ID </li>
            <li> and any further challenge-specific columns required for the answer</li>.
          </ul>
        </p>
        </li>
        <li>
          <h4>3. Create the UI code </h4>

          <p>
            Create the UI to present the task and collect the data using the <a href="/framework">javascript framework.</a> No need to install something. Code
            online. The code is also saved to GIST to manage the versioning.
            <img src='/assets/editor.jpg' style="width:100%;border: 1px solid black"/>
          </p>
        </li>


        <li><h4>4. Enjoy !</h4>
          <p>
          Your app is ready. You can embed the app on your web site or display its QRcode so people can complete tasks via their mobile phones. <br/>Note: You can still improve/update the source code. the app will be automatically updated.
        </p>
        </li>
      </ol/>

app/views/apps/dashboard.html.erb
<% @app_header = capture do %>
<ul class="nav">
    <li><a href="/apps">Explore apps</a></li>
    <li><%= link_to @app.name[0..20], app_path(@app) %></li>
    <li class="active" ><a href="#">dashboard</a></li>
</ul>
<% end %>

<% content_for :menu_header, @app_header %>
<style>
  section{ margin-top:10px; }
</style>

<div class="container">
  <div class="row">
    <div class="span12">
        <% unless notice.blank? %>
        <div class="alert alert-block alert-success fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p><%= notice %></p>
        </div>
      <% end %>
    <h3><%= @app.name %>   <% if @app.user == current_user %>
       <a href="<%= edit_app_path(@app) %>" class="btn btn-mini">setting</a>
        <%= link_to 'delete', @app, confirm: 'Are you sure?', method: :delete, :class => "btn btn-mini btn-danger" %>
      <% end %>
    </h3>

  </div>
  </div>
  <div class="row">
    <div class="span2">

      <section>
        <img src="<%= app_path(@app,:format=>"png") %>" width="100%" />
      </section>

      <section>
        <h4>challenges answered</h4>
        <% completion = @app.completion %>
        <% if completion[:total] == 0 %>
        No challenge indexed
        <% else %>
        <%= completion[:completed] %> / <%= completion[:total] %>
        <div class="progress progress-info  progress-striped">
          <div class="bar" style="width: <%= completion[:completed] *100/completion[:total] %>%;"></div>
        </div>
        <% end %>
      </section>

      <section>
        <h4>Last solvers</h4>
        <ul style="padding: 0px;margin: 0; margin-top: 3px;">
          <% @app.contributors.order('users.updated_at desc').limit(5).each { |u| %>
              <li style="list-style-type: none;">
                <%= gravatar_image_tag(u.email, :title => u.username, :gravatar => {:default => :identicon, :size => 30}) %>
            <%= time_ago_in_words(u.updated_at) %> ago
              </li>
          <% } %>
        </ul>
      </section>
    </div>
    <div class="span9">
     <% @button_size = "btn-mini" %>
     <%= render "shared/menu.html" %>
     <iframe scrolling="no" src="<%= app_url(@app) %>" style="width:<%= @app.iframe_width %>;height:<%= @app.iframe_height %>;padding:0;border:1px solid black"></iframe>
    </div>
  </div>
</div>

<script type='text/javascript' src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js"></script>
<script type='text/javascript' src='http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js'></script>
<script type="text/javascript">
    $(function () {
        $('#myTab a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        });

        $("a[rel=div]").click(function (e) {
            e.preventDefault();
            $($(this).attr("href")).toggle();
        });
         $(".alert").alert();
    });
</script>

app/views/apps/debug.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MechanicalMap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
  <!-- bootstrap
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
  -->

  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js"></script>

  <script type="text/javascript">
      var user = {id:<%= current_or_guest_user.id %>, name:"<%= current_or_guest_user.username %>"};
      var scheduler_url = "<%= workflow_app_url(@app) %>";
      var application_url = "<%= app_url(@app) %>";
      var ft_table = "<%= @app.input_ft %>";
      //dynamically resize the map
  </script>

</head>

<body>
<div class="container">
  <div
</div>
<!-- BEGINNING OF The UI Task TEMPLATE
================================================== -->
<!-- schema=[{name:"task_id", type:"number"},{name:"user_id", type:"number"},{name:"relevance", type:"number"}] -->

<div id="info">
  <img id="image" src="http://www.langues-jonquiere.ca/images/images/loading.gif" style="max-height: 100%;max-width: 100%">
</div>

<div id="menu" style="height:80px;display:block;margin: 0;padding: 0;clear: both">
  <p> This photo has been taken during the libya conflict and published on <a href='#' id="webpage"> this web page</a>.
    <br/>Does this image show damaged buildings?</p>

  <div class='row'>

    <div class="span3">
      <form accept-charset="UTF-8" action="" id="form_task" class="edit_task navbar-form pull-left" data-remote="true" data-type="json" id="submit_task" method="put">
        <input id="task_answer" name="task_answer" type="hidden"/>
        <button type="button" id='yes_button' class="btn" data-disable-with="Saving..." name="relevant">Yes</button>
        <button type="button" id='no_button' class="btn" data-disable-with="Saving..." name="not_relevant">no</button>
        <a id='skip_task' class="btn btn-small" href="#">Next photo</a>
      </form>
    </div>
    <div class="span3">
      <div class="block-helper">
        <small>Task completeness</small>                               </div>
      <div class="progress" style="width:100px;height: 10px">
        <div class="bar" id="progress_bar" style="width: 10%;color:black;font-size: smaller;padding: 0;margin: 0"></div>
      </div>
    </div>
    <div class="span3"><span id="task_user_id"></span></div>
  </div>
</div>


<!-- javascript
================================================== -->
<script type="text/javascript">
    // Global variables

    var micro_task;
    var relevance;

    function submit_vote(vote) {
        relevance = vote;
        $("#form_task").submit();
    }

    function resize_image() {
        // calculate new size and apply it
        var max_h = $(window).height();
        var max_w = $(window).width();
        var m_h = $("#menu").height();
        $("#info").height(max_h - m_h);
    }


    $(function() {

        // initializing the UI
        $("#yes_button").click(function() {
            submit_vote(1);
        });
        $("#no_button").click(function() {
            submit_vote(-1);
        });
        $("#image").load(resize_image);

        // initializing the task manager
        // we have to manage the loading and saving of a task
        micro_task = new FTMicroTask({
            scheduler_url:scheduler_url,
            ft_table:ft_table,
            load:function(ft_data) {
                console.log(ft_data);
                // parse specific task info
                var image_url = ft_data.table.rows[0][1];
                $("#image").attr('src', image_url);
                var web_page_url = ft_data.table.rows[0][2];
                $("#webpage").attr('href', web_page_url);
            },
            save:function() {
                var rows = [];
                rows.push({
                    user_id :user.id,
                    task_id: micro_task.task.input,
                    relevance: relevance});
                $("#task_answer").val(JSON.stringify(rows));
            }
        });
        micro_task.start();
        resize_image();
    });
</script>

<!--END  UI Task TEMPLATE
================================================== -->
</body>
</html>

app/views/apps/edit.html.erb
<% app_header = capture do %>
<ul class="nav">
	<li> <a href="/apps">Explore apps</a></li>
	<li class="dropdown">
    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= @app.name[0..20] %> <b class="caret"></b></a>
		<%= render 'app_menu' %>
	</li>
</ul>
<% end %>
<% content_for :menu_header, app_header %>
<% @edit = true %>
<div class="container">
	<%= render 'form2' %>
</div>

app/views/apps/editor.html.erb
<% @header = capture do %>

<%= form_for(@app, :url => {:action => "editor_update"}, :html => {:id => "form_app"}, :remote => true) do |f| %>

    <input type="hidden" name="app[script]" id="app_script" value=""/>
<div class="nav">
    <button class="btn btn-primary" data-disable-with="Saving..."
            id="update"
            <% if @app.user!=current_user %> disabled="true"
            <% end %>>Update code
    </button>
  </div>
     <% if @app.gist_id %>

<ul class="nav">  <li>
    <a href="https://gist.github.com/<%= @app.gist_id %>" target="_blank" class="">Gist History</a>
  </li></ul>
</div>
  <% end %> 
    <% end %>

  

<% end %>

<% content_for :header, @header %>

<% @app_header = capture do %>
    <li><%= link_to @app.name[0..20], app_path(@app) %></li>
 
<% end %>
<% content_for :app_header, @app_header %>

  <style type="text/css" media="screen">


      body {

      }
      form{
        margin:0px;
      }
      #editor {
          margin: 0;
          top: 40px;
          bottom: 0;
          left: 0;
          right: 0;
      }
  </style>



  
    <div id="editor"><%= @app.script %></div>



<%= javascript_include_tag "application" %>
<!--<script  src="/assets/ace/ace-noconflict.js" type="text/javascript" charset="utf-8"></script>-->

<script src="/assets/ace/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/ace/theme-chrome.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/ace/mode-html.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    // Global variables
    var editor;


    // Register an event listener to fire when the page finishes loading.
    $(function () {

      $("#form_app").submit(function () {
            var text = editor.getSession().getValue();
            $("#app_script").val(text);
            return true;
      });
        editor = ace.edit("editor");
        editor.setTheme("ace/theme/chrome");
        var Mode = require("ace/mode/html").Mode;
        editor.getSession().setMode(new Mode());
        // editor.getSession().setMode("ace/mode/html");

    });
</script>

app/views/apps/embed.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="http://cdn.androidblip.com/icn/com_defiant_supermarioentertainment____90218.png" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= raw @app.name %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
    <%= javascript_include_tag "application" %>
    <script src="http://underscorejs.org/underscore<%= (Rails.env == "production")?
    "-min" : "" %>.js"></script>
    <script src="http://backbonejs.org/backbone<%= (Rails.env == "production")?
    "-min" : "" %>.js"></script>
    <%= javascript_include_tag "app" %>


    <script type="text/javascript">
    //var underscore = _.noConflict();
    var user = {name:"<%= current_or_guest_username %>"};
    var application_url = "<%= app_url(@app) %>";
    </script>
  </head>
  <body>
     <%= raw @app.script %>
  </body>
</html>

app/views/apps/index.html.erb
<% app_header = capture do %>
<ul class="nav">
  <li class="active"> <a href="/apps">Explore apps</a></li>
  <li ><a href="/apps/new">Create an app</a></li>
</ul>
<% end %>
<% content_for :menu_header, app_header %>

<div class="container">
  <div class="page-header">
    <h1>Explore Crowdsourcing Apps</h1>
  </div>
  <ul class="thumbnails">

  <% @start = false
  @apps.each_with_index do |app, i|
    #completed, size= @app.completion
    @app = app %>
    <li class="span4">
      <div class="thumbnail">
        <img src="<%= @app.image_url %>" style="height:200px;width:320px;"/>
        <div class="caption">
          <h4><%= app.name %> </h4>
          <small> created <%= time_ago_in_words(app.created_at) %> ago</small>
          <p><%=  app.description.html_safe %></p>
          <p>
              <div class="dropdown" >
            <a href="<%= app_url(app) %>" class="btn btn-primary">Start</a>

              <a id="drop_<%= i %>" href="#" role="button" class="btn dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
             <%= render "app_menu" %>

            </div>
          </p>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
</div>
<% script = capture do %>
<script type="text/javascript">
 $('.dropdown-toggle').dropdown();
 </script>
<% end %>
<% content_for :script, script %>

app/views/apps/more.html.erb
<div class="container">
  <div id="actions" style="margin:auto;width:500px;text-align:center">
    <h1> Creating a new crowdsourcing app </h1>
    <p style="margin-top:10px;">
      Create a crowdsourcing app in few minutes: clone existing apps (data+code), edit online the code or the data and embed your app on your own web site like a youtube video. Zero installation/server is required thanks to the cloud infrastructure.
    </p>
    <p>
      <a href="/apps/new" class="btn btn-primary btn-large"> from scratch</a>
      <a href="/apps" class="btn btn-large">Clone an app</a>
    </p>
  </div>
</div>

<!--
<div class="container">
       <h4> How does it work internally?</h4>
          Once the indexation of the GF tasks table done and a GF answers table generated, the framework will organize the tasks using a <i>parallel model</i>.
          <br/>In a parallel model, a set of volunteers performs independently the same task.
          So, according to the redundancy criteria provided during the creation of the app, each task will be assigned to 1 or several users. furthermore in this model a post data processing is generally required to aggregate the answers of different users (e.g. average or consensual) in order to generate a collective output.

          <br/>A parallel model is generally fine for simple tasks but certainly limited for more complex ones.  <a href="http://nico.maisonneuve.free.fr/blog/index.php/2012/crowdsourcing-satellite-imagery-part-2-iterative-vs-parallel-human-organisations/">Other models of organisation</a> are possible and a "organisation design" tool will be developed if I have time. Below an example of a parallel model to annotate maps collaboratively, fitting with the GIS

          <img src="https://docs.google.com/uc?id=0B1tvqho7IAWdYWJjdWhQdll2TUU" class="span7"/>

    <img src='/assets/architecture.jpg' style='width:100%;border:1px solid black' />
   <div class="span3">
        <img src="https://docs.google.com/drawings/pub?id=1fvbDL2pcMHqWn9B8o1D33EPAdF3vK7-UozXpEbn8XyQ&amp;w=800" class="span6">

      <img src="https://docs.google.com/drawings/pub?id=1b7udWkfMXof2l-jzzYV6FThdupTpIPZEVULsfnM8hak&amp;w=350&amp;h=600">

    </div>
</div>
 -->

app/views/apps/new.html.erb
<% app_header = capture do %>
<ul class="nav">
	<li> <a href="/apps">Explore apps</a></li>
	<li class="active"><a href="/apps/new">Create an app</a></li>
</ul>
<% end %>
<% content_for :menu_header, app_header %>
<% @edit = false %>

<div class="container">
	<%= render 'form2' %>
</div>

app/views/apps/show.html.erb
<% app_header = capture do %>
<ul class="nav">
  <li> <a href="/apps">Explore apps</a></li>
    <li class="dropdown">
      <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= @app.name[0..20] %> <b class="caret"></b></a>
      <%= render "app_menu" %>
    </li>
  </ul>
<% end %>
<% content_for :menu_header, app_header %>
<div class="container">
<iframe scrolling="no" id="app_iframe" src="<%= embed_app_url(@app) %>" style="padding:0;border:0px;margin:0px"></iframe>
</div>
<% script = capture do %>
<!--<script type="text/javascript" src="https://raw.github.com/Sly777/Iframe-Height-Jquery-Plugin/master/Src/iframeheight.min.js"></script> -->
<script type="text/javascript">
  $(function () {
    $('.dropdown-toggle').dropdown();
    $("#app_iframe").width("<%= @app.iframe_width %>");
    <% if ((@app.iframe_height == "100%") and (@app.iframe_width == "100%"))  %>
    $("#app_iframe").height($(document).height()-45);
    <% else %>
    $("#app_iframe").height("<%= @app.iframe_height %>");
    <% end %>
  });
</script>
<% end %>
<% content_for :script, script %>

app/views/apps/source.html.erb
<% header = capture do %>
  <ul class="nav">
    <li> <a href="/apps">Explore apps</a></li>
     <li class="dropdown">
    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><%= @app.name[0..20] %> <b class="caret"></b></a>
    <%= render 'app_menu' %>
  </li>

    <li>
      <a href="<%= @app.gist_url %>" target="_blank" class=""><b class=" icon-list-alt"></b> Gist / History</a>
    </li>
  </ul>

  <%= form_for(@app, :url => {:action => "source_update"}, :html => {:id => "form_app"}, :remote => true) do |f| %>
    <input type="hidden" name="app[script]" id="app_script" value=""/>
    <div class="nav">
      <button class="btn btn-primary" data-disable-with="Saving..."
              id="update"> Save code
      </button>
    </div>
  <% end %>
<% end %>

<% content_for :menu_header, header %>

<style type="text/css" media="screen">
  form { margin:0px; }
  #editor {
      margin: 0;
      top: 40px;
      bottom: 0;
      left: 0;
      right: 0;
  }
</style>

<div id="editor"><%= @app.script %></div>


<% script = capture do %>

<script type="text/javascript">
    // Global variables
    var editor;
    var code_changed = false
    $('.dropdown-toggle').dropdown();

    function save(){
        var text = editor.getSession().getValue();
        $("#app_script").val(text);
        code_changed = false;
        $("#update").attr("disabled",true);
        return true;
    }

    // Register an event listener to fire when the page finishes loading.
    $(function () {
      $("#form_app").submit(save);

      editor = ace.edit("editor");
      editor.setTheme("ace/theme/chrome");
      var Mode = require("ace/mode/html").Mode;
      editor.getSession().setMode(new Mode());
      editor.getSession().setUseSoftTabs(true);
      editor.getSession().setTabSize(2);
      editor.commands.addCommand({
        name: 'mySave',
        bindKey: {win: 'Ctrl-S',  mac: 'Command-S'},
          exec: function(editor) {
            $("#form_app").submit();
          }
      });
      editor.getSession().on('change', function(){
        code_changed = true;
        $("#update").attr("disabled",null);
      });

      // we save every minute
      (function(){
        // do some stuff
        if (code_changed){
          $("#form_app").submit();
        }
        setTimeout(arguments.callee, 60000);
      })();
    });
 </script>
<% end %>
<% content_for :script, script %>